# Generated by Django 4.2.30 on 2026-07-16 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('icon', models.CharField(blank=True, help_text="Classe FontAwesome (ex: 'fas fa-wifi')", max_length=100, verbose_name='Icône FontAwesome')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
            ],
            options={
                'verbose_name': 'Équipement',
                'verbose_name_plural': 'Équipements',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('slug', models.SlugField(help_text='Identifiant URL unique. Laisser vide pour auto-génération.', max_length=200, unique=True, verbose_name='Slug')),
                ('subtitle', models.CharField(blank=True, max_length=300, verbose_name='Sous-titre')),
                ('summary', models.TextField(help_text="Affiché sur la page d'accueil et dans les listes", max_length=500, verbose_name='Résumé court')),
                ('description', models.TextField(verbose_name='Description complète')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publié'), ('hidden', 'Masqué')], default='draft', max_length=20, verbose_name='Statut')),
                ('featured', models.BooleanField(default=False, verbose_name='Mis en avant')),
                ('order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('city', models.CharField(default='Royan', max_length=100, verbose_name='Ville')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='Adresse')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Latitude')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Longitude')),
                ('distance_to_beach', models.CharField(blank=True, max_length=100, verbose_name='Distance plage')),
                ('max_guests', models.PositiveIntegerField(default=4, verbose_name='Voyageurs max')),
                ('bedrooms', models.PositiveIntegerField(default=2, verbose_name='Chambres')),
                ('beds', models.PositiveIntegerField(default=2, verbose_name='Lits')),
                ('bathrooms', models.PositiveIntegerField(default=1, verbose_name='Salles de bain')),
                ('surface_area', models.CharField(blank=True, help_text="ex: '60 m² + 20 m²'", max_length=100, verbose_name='Surface')),
                ('base_price', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Prix de base / nuit')),
                ('cleaning_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Frais de ménage')),
                ('security_deposit', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Caution')),
                ('currency', models.CharField(default='€', max_length=10, verbose_name='Monnaie')),
                ('check_in_time', models.CharField(default='À partir de 16:00', max_length=50, verbose_name="Heure d'arrivée")),
                ('check_out_time', models.CharField(default='Avant 10:00', max_length=50, verbose_name='Heure de départ')),
                ('house_rules', models.TextField(blank=True, verbose_name='Règles de la maison')),
                ('host_name', models.CharField(blank=True, max_length=100, verbose_name="Nom de l'hôte")),
                ('registration_number', models.CharField(blank=True, max_length=50, verbose_name="Numéro d'enregistrement")),
                ('meta_title', models.CharField(blank=True, help_text='Titre SEO (70 car. max)', max_length=70, verbose_name='Meta title')),
                ('meta_description', models.CharField(blank=True, help_text='Description SEO (160 car. max)', max_length=160, verbose_name='Meta description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('amenities', models.ManyToManyField(blank=True, to='properties.amenity', verbose_name='Équipements')),
            ],
            options={
                'verbose_name': 'Propriété',
                'verbose_name_plural': 'Propriétés',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='properties/', verbose_name='Image')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='Texte alternatif')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Image principale')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property', verbose_name='Propriété')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
                'ordering': ['order'],
            },
        ),
    ]
