# Generated by Django 4.2.30 on 2026-07-18 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='Nom')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('check_in', models.DateField(verbose_name="Date d'arrivée")),
                ('check_out', models.DateField(verbose_name='Date de départ')),
                ('guests', models.PositiveIntegerField(default=1, verbose_name='Voyageurs')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Prix total')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmée'), ('cancelled', 'Annulée'), ('completed', 'Terminée')], default='pending', max_length=20, verbose_name='Statut')),
                ('source', models.CharField(choices=[('direct', 'Réservation directe'), ('airbnb', 'Airbnb'), ('booking_com', 'Booking.com')], default='direct', max_length=20, verbose_name='Source')),
                ('payment_status', models.CharField(choices=[('unpaid', 'Impayé'), ('paid', 'Payé'), ('refunded', 'Remboursé')], default='unpaid', max_length=20, verbose_name='Paiement')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créée le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mise à jour le')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='properties.property', verbose_name='Propriété')),
            ],
            options={
                'verbose_name': 'Réservation',
                'verbose_name_plural': 'Réservations',
                'ordering': ['-created_at'],
            },
        ),
    ]
