# Generated by Django 4.2.30 on 2026-07-18 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_add_booking_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='ICalSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='ex: Airbnb, Booking.com', max_length=100, verbose_name='Nom')),
                ('url', models.URLField(max_length=500, verbose_name='URL iCal')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('last_synced', models.DateTimeField(blank=True, null=True, verbose_name='Dernière synchro')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ical_sources', to='properties.property', verbose_name='Propriété')),
            ],
            options={
                'verbose_name': 'Source iCal',
                'verbose_name_plural': 'Sources iCal',
            },
        ),
        migrations.CreateModel(
            name='BlockedPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('end_date', models.DateField(verbose_name='Date de fin')),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='ID externe')),
                ('summary', models.CharField(blank=True, max_length=255, verbose_name='Résumé')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_periods', to='properties.icalsource', verbose_name='Source iCal')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_periods', to='properties.property', verbose_name='Propriété')),
            ],
            options={
                'verbose_name': 'Période bloquée',
                'verbose_name_plural': 'Périodes bloquées',
                'indexes': [models.Index(fields=['unit', 'start_date', 'end_date'], name='properties__unit_id_c08558_idx')],
            },
        ),
    ]
