# Generated by Django 4.2.30 on 2026-07-19 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_ical_sync'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='translations',
            field=models.JSONField(blank=True, default=dict, help_text="Contenu multilingue — {'fr': {'name': '...', 'subtitle': '...'}, 'en': {'name': '...'}}", verbose_name='Traductions'),
        ),
    ]
