# Generated by Django 4.2.30 on 2026-07-19 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_add_test_ical_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='ex: Haute saison, Pont de mai...', max_length=100, verbose_name='Nom')),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('end_date', models.DateField(verbose_name='Date de fin')),
                ('nightly_price', models.DecimalField(blank=True, decimal_places=2, help_text='Laissez vide pour utiliser le prix de base', max_digits=8, null=True, verbose_name='Prix par nuit (€)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='properties.property', verbose_name='Propriété')),
            ],
            options={
                'verbose_name': 'Saison / période',
                'verbose_name_plural': 'Saisons / périodes',
                'ordering': ['start_date'],
            },
        ),
    ]
