# Generated by Django 4.2.30 on 2026-07-16 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='Nom')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('subject', models.CharField(choices=[('reservation', 'Réservation'), ('information', "Demande d'information"), ('disponibilite', 'Vérification de disponibilité'), ('tarif', 'Demande de tarif'), ('reclamation', 'Réclamation'), ('autre', 'Autre')], max_length=50, verbose_name='Sujet')),
                ('property_interest', models.CharField(blank=True, max_length=50, verbose_name='Logement concerné')),
                ('message', models.TextField(verbose_name='Message')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lu')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Reçu le')),
            ],
            options={
                'verbose_name': 'Message de contact',
                'verbose_name_plural': 'Messages de contact',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Inscrit le')),
            ],
            options={
                'verbose_name': 'Abonné newsletter',
                'verbose_name_plural': 'Abonnés newsletter',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('template', models.CharField(choices=[('about', 'À propos'), ('contact', 'Contact'), ('faq', 'FAQ'), ('local_guide', 'Guide local'), ('legal', 'Mentions légales'), ('privacy', 'Politique de confidentialité'), ('custom', 'Personnalisée')], default='custom', help_text="Sélectionnez le template à utiliser pour l'affichage", max_length=50, verbose_name='Template')),
                ('content', models.TextField(blank=True, help_text='Contenu de la page (HTML autorisé)', verbose_name='Contenu')),
                ('meta_title', models.CharField(blank=True, help_text='Titre SEO', max_length=70, verbose_name='Meta title')),
                ('meta_description', models.CharField(blank=True, help_text='Description SEO', max_length=160, verbose_name='Meta description')),
                ('is_published', models.BooleanField(default=True, verbose_name='Publiée')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créée le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mise à jour le')),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
                'ordering': ['order', 'title'],
            },
        ),
    ]
