# Generated by Django 4.2.30 on 2026-07-17 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='terms_accepted',
            field=models.BooleanField(default=False, verbose_name='CGV acceptées'),
        ),
    ]
