# Generated by Django 4.2.30 on 2026-07-19 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_contactmessage_terms_accepted'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text="Identifiant unique (ex: 'hero_title', 'about_intro')", max_length=100, unique=True, verbose_name='Clé')),
                ('label', models.CharField(help_text="Description lisible de ce champ dans l'admin", max_length=200, verbose_name='Libellé')),
                ('translations', models.JSONField(blank=True, default=dict, help_text="Contenu multilingue — {'fr': 'Bonjour', 'en': 'Hello'}", verbose_name='Traductions')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
            ],
            options={
                'verbose_name': 'Texte du site',
                'verbose_name_plural': 'Textes du site',
                'ordering': ['key'],
            },
        ),
    ]
